# Generated by Django 2.2 on 2019-04-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190403_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_type', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=128)),
                ('album_art', models.ImageField(upload_to='', verbose_name='Album Cover')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=128)),
                ('total_tracks', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name='Artist Photo')),
                ('spotify_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_ms', models.PositiveIntegerField()),
                ('spotify_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('track_number', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Album')),
                ('artist', models.ManyToManyField(to='accounts.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('album', models.ManyToManyField(to='accounts.Album')),
                ('artist', models.ManyToManyField(to='accounts.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='accounts.Artist'),
        ),
    ]
