# Generated by Django 2.2 on 2019-04-09 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
        migrations.AddField(
            model_name='genre',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Album Cover'),
        ),
    ]
