# Generated by Django 2.2 on 2019-04-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190409_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='album',
            new_name='albums',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='artist',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artists',
        ),
    ]
