# Generated by Django 2.2 on 2019-04-22 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190422_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genres',
        ),
        migrations.AddField(
            model_name='artist',
            name='users',
            field=models.ManyToManyField(related_name='artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='users',
            field=models.ManyToManyField(related_name='genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
