# Generated by Django 2.2 on 2019-04-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190422_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_art',
        ),
        migrations.AddField(
            model_name='album',
            name='art_large',
            field=models.CharField(default='asdfasdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='art_medium',
            field=models.CharField(default='asdfasdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='art_small',
            field=models.CharField(default='asdfasdf', max_length=255),
            preserve_default=False,
        ),
    ]
